services:
  - type: web
    name: digiman-modular
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn api.digiman_server:app --bind 0.0.0.0:$PORT
    healthCheckPath: /digiman/ping
